{
 "title": "Stats network/area level",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "RPL", "query": "select RPL from stats_area;" },
   { "name": "Area", "query": "select Area from stats_area;" }
  ]
 },
 "panels": [
  {
   "title": "Mons scanned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#Mons" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  sum(Mons_all) AS \"Mons_all\",\n  sum(MonsIV) AS \"MonsIV\"\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY Datetime\nORDER BY $__timeGroup(Datetime,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(MonsIV)/sum(Mons_all) AS '% IV'\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Restart/reboot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  sum(a.Reb) AS \"Reboots\",\n  sum(a.Res) AS \"Restarts\"\nFROM stats_worker a, Area b\nWHERE\n  a.RPL = '$RPL' and\n  a.Worker = b.Origin and\n  b.Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Spawnpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(DBspawns) AS \"DBspawns\",\n  sum(Last_scanned_today_acc) AS \"Scanned today\",\n  sum(Spawn_add) AS \"Spawns added\",\n  sum(Spawn_NULL) AS \"Spawns unknown\"\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Spawns unseen details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(Last_scanned_1d) AS \"Last scanned yesterday\",\n  sum(Last_scanned_2d) AS \"Last scanned 2d ago\",\n  sum(Last_scanned_3d) AS \"Last scanned 3d ago\",\n  sum(Last_scanned_7dp) AS \"Last scanned >7d ago\"\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Spawndef",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(Spawndef15) AS \"60m spawn\",\n  sum(SpawndefNot15) AS \"30m spawn\"\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Despawn time left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(w5)/sum(Mons_all) AS '% scanned within 5m',\n  100*sum(w10)/sum(Mons_all) AS '% scanned within 10m',\n  100*sum(w15)/sum(Mons_all) AS '% scanned within 15m',\n  100*sum(w20)/sum(Mons_all) AS '% scanned within 20m'\nFROM stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(MinutesLeft)/((sum(Spawndef15) * 60)+(sum(SpawndefNot15) * 30)) AS \"%time left\"\nFROM pogodb.stats_area\nWHERE\n  RPL = '$RPL' and\n  Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Location handling (1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  sum(a.Tloc) AS \"#Locations handled\",\n  sum(a.Tp) AS \"#Teleports\",\n  sum(a.Wk) AS \"#Walk\"\nFROM stats_worker a, Area b\nWHERE\n  a.RPL = '$RPL' and\n  a.Worker = b.Origin and\n  b.Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Location handling (2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  100*sum(a.LocOk)/sum(a.Tloc) AS \"Location Success Rate\",\n  100*sum(a.TpOk)/sum(a.Tp) AS \"Teleport Success Rate\",\n  100*sum(a.WkOk)/sum(a.Wk) AS \"Walk Success Rate\"\nFROM stats_worker a, Area b\nWHERE\n  a.RPL = '$RPL' and\n  a.Worker = b.Origin and\n  b.Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Quest scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  sum(a.Quest) AS \"Quest\"\nFROM stats_worker a, Area b\nWHERE\n  a.RPL = '$RPL' and\n  a.Worker = b.Origin and\n  b.Area in ($Area)\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  }
 ]
}