{
 "title": "Stats KPIs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "RPL", "query": "select RPL from stats_area;" }
  ]
 },
 "panels": [
  {
   "title": "Mons scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#Mons" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  sum(Mons_all) AS \"Mons scanned\",\n  100*sum(a.MonsIV)/sum(a.Mons_all) AS \"%IV scanned\"\nFROM stats_area a\nWHERE\n  a.RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(TRPL)/sum(RPL) AS \"% Uptime\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "#Devices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  count(Worker) AS \"#devices\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Restart / Reboot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# restarts /h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(Res)/(count(distinct(Worker))*$RPL/60) AS \"Avgerage # Pogo restarts per hour\",\n  sum(Reb)/(count(Worker)*$RPL/60) AS \"Avgerage # device reboots per hour\"\nFROM stats_worker\nWHERE\n  RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Despawn time left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "% despawn time left" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(a.Datetime,$__interval),\n  100*sum(a.MinutesLeft)/((sum(a.Spawndef15) * 60)+(sum(a.SpawndefNot15) * 30)) AS \"%despawntime left\"\nFROM stats_area a\nWHERE\n  a.RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(a.Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Location handling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(LocOk)/sum(Tloc) AS \"Location Success Rate\",\n  100*sum(TpOk)/sum(Tp) AS \"Teleport Success Rate\",\n  100*sum(WkOk)/sum(Wk) AS \"Walk Success Rate\"\nFROM stats_worker\nWHERE\n  RPL = '$RPL'\nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  }
 ]
}