{
 "title": "Stats worker level",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RPL",
    "query": "select distinct(RPL) from stats_worker;"
   },
   {
    "name": "Worker",
    "query": "select distinct(Worker) from stats_worker;"
   }
  ]
 },
 "panels": [
  {
   "title": "Mons scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Datetime AS \"time\",\n  sum(Tmon) AS 'Mons scanned',\n  sum(IVmon) AS 'IV scanned',\n  100*sum(IVmon)/sum(Tmon) AS '%IV'\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL='$RPL' and\n  Worker in ($Worker)\nGROUP BY Datetime  \nORDER BY Datetime"
    }
   ]
  },
  {
   "title": "Restart / Reboot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(res) AS \"# pogo restarts\",\n  sum(reb) AS \"#device reboots\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL' and\n  Worker in ($Worker)\nGROUP BY Datetime\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Location handling (1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(Tloc) AS \"Locations handled\",\n  sum(Wk) AS \"#walking\",\n  sum(Tp) AS \"#teleports\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL' and\n  Worker in ($Worker)\nGROUP BY Datetime\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Location handling (2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  100*sum(LocOk)/sum(Tloc) AS \"Location success rate\",\n  100*sum(WkOk)/sum(Wk) AS \"Walk success rate\",\n  100*sum(TpOk)/sum(Tp) AS \"Teleport Success Rate\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL' and\n  Worker in ($Worker)\nGROUP BY Datetime\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Quest scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Datetime,$__interval),\n  sum(Quest) as \"#Quests scanned\"\nFROM stats_worker\nWHERE\n  $__timeFilter(Datetime) and\n  RPL = '$RPL' and\n  Worker in ($Worker)\nGROUP BY Datetime\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  }
 ]
}